services:
  - type: web
    name: swiftpos-vision-api
    env: python
    rootDir: swiftpos-vision/server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MPLCONFIGDIR
        value: /tmp
      - key: YOLO_CONFIG_DIR
        value: /tmp
